networks:
  frontend:
    external: true
  backend:

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx_trading
    volumes:
      - .:/var/www/trading
    environment:
      - VIRTUAL_HOST=trading.test
    ports:
      - "80:80"
    networks:
      frontend:
      backend:
        aliases:
          - trading.test

  php:
    build: ./docker/php
    container_name: php_trading
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/trading
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    networks:
      frontend:
      backend:
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/trading:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
      - frontend
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  supervisor:
      build: ./docker/supervisor
      container_name: supervisor_trading
      networks:
          - backend
      volumes:
          - .:/var/www/trading
          - ./storage/logs:/var/log/php
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
          - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
